# -*- coding: utf-8 -*-

LANG_KEY = u"DE"
LANG_NATIVE_NAME = u"Deutsch"

KWDS = {
"MSG_FORMAT_DEFAULT":       u"Standard: E-Mail [Betreff] Nachricht, Link",
"MSG_FORMAT_WO_LINK":       u"ohne_Link: E-Mail [Betreff] Nachricht",
"MSG_FORMAT_LINK_ONLY":     u"Nur_Link: E-Mail [Betreff] Link",
"MSG_FORMAT_SHORT":         u"kurz: Betreff",
"CHANGE_MSG_FORMAT":        u"/msg_format - Ändere das Nachrichtenformat",
"CHANGE_SUBJ_RULES":        u"/subj_rules - Betreff Bedingungen",
"CHANGE_BODY_RULES":        u"/body_rules - Verarbeitungsregeln",
"HIDE_KEYBOARD":            u"/hide - Diese Leisten verbergen",
"GO_PAY":                   u"Zum Bezahlsystem gehen",
"CANCEL":                   u"Abbruch",
"REMOVE_RULES_BUTTON":      u"Alle Regeln entfernen",
"CHECK_PAYMENT":            u"Überprüfe den Status der Zahlung",
"CONFIRM_ORDER":            u"Aktion bestätigen",
"SUCCESS_PAYMENT":          u"> Super! Der Nutzername {} gehört nun dir. Du kannst jetzt alle deine verschiedenen E-Mail Adressen unter /addresses sehen",
"NOT_PAID":                 u"> Immer noch nicht bezahlt!",
"CANCELLED":                u"> Abgebrochen",
"ENTER_SUBJ":               u"> Schreibe bitte den Betreff:",
"ENTER_SUBJ_ERR":           u"> Leider ist ein Fehler während der Eingabe des Betreffs aufgetreten",
"ENTER_MSG":                u"> Schreibe nun deinen Nachrichtentext:",
"ENTER_MSG_ERR":            u"> Leider ist ein Fehler während der Eingabe des Textes aufgetreten. Versuche es erneut:",
"MSG_SENT":                 u"> Die E-Mail wurde versendet!",
"MSG_QUEUED":               u"> Die E-Mail wurde erfolgreich versendet",
"MSG_NOT_SENT":             u"> Die E-Mail wurde nicht versendet",
"MSG_ERROR_SENT":           u"> Leider ist während dem Sendevorgang ein Fehler aufgetreten",
"INCORR_SYMB":              u"> Ungültige Zeichen! Versuche bitte, andere zu verwenden:",
"NAME_TAKEN":               u"> Dieser Nutzername ist leider schon vergeben! Versuche es mit einem anderen:",
"TRANS_ISSUE":              u"> Fehler bei der Transaktion. Bitte kontaktiere den Support: @adastreamer",
"PAY_CALL":                 u"> Fertig! Deine E-Mail Adresse ist soweit bereit und fertig eingerichtet. Du brauchst nur noch zu bestätigen.",
"PAY_BUTTON":               u"Veranlasse eine Zahlung",
"HI":                       u"> Hallo, deine standardmäßige E-Mail Adresse für diesen Chat lautet: {}@etlgr.com {}",
"HI_POSTFIX":               u" (Minus ist ein Teil der Adresse)",
"ENTER_SENDER":             u"> Wähle bitte die Adresse aus, von der du deine E-Mail versenden möchtest:",
"ENTER_SENDER_WRONG":       u"> Dies ist nicht deine Adresse. Wähle bitte eine der unten stehenden, dir gehörenden, Adresse aus:",
"ENTER_EMAIL":              u"> Schreibe nun die E-Mail Adresse(n), an die du die Nachricht versenden möchtest:",
"ENTER_EMAIL_ERR":          u"> Leider ist ein Fehler aufgetreten. Du kannst bis zu 5 Empfänger auswählen:",
"CHOOSE_NAME":              u"> Wähle bitte einen Nutzernamen aus (z.B. andrew):",
"ADDRESSES_LIST_BASE":      u"> Deine E-Mail Adressen:",
"CHOOSE_ACTION":            u"> Wähle eine Aktion aus:",
"CHOOSE_LANG":              u"> Wähle eine Sprache aus:",
"GET_ADDRESS":              u"/start - Standard E-Mail Adresse anzeigen",
"CHANGE_LANG":              u"/lang - Spräche ändern",
"SEND_MSG":                 u"/send - E-Mail versenden",
"REGISTER_OWN":             u"/register - Erstelle eine personalisierte Adresse",
"GET_ADDRESSES":            u"/addresses - Deine E-Mail Adressen",
"CHOOSE_RELEASE_ADDRESS":   u"> Wähle die E-Mail Adresse aus, die du entfernen/freigeben möchtest:",
"NO_ADDRESS_TO_RELEASE":    u"> Du hast keine personalisierten E-Mail Adressen. Erstelle eine über /register",
"RELEASE":                  u"/release - Entferne deine personalisierte E-Mail Adresse",
"WRONG_RELEASE_ADDRESS":    u"> Falsche E-Mail Adresse. Versuche es erneut:",
"RELEASED_CHOOSE_ACTION":   u"> E-Mail Adresse erfolgreich entfernt/freigegeben! Wähle eine Aktion aus:",
"KEYBOARD_HIDDEN":          u"> Die Leisten sind nun versteckt. Tippe /start , um sie wieder anzuzeigen",
"CHOOSE_MSG_FORMAT":        u"> Wähle das Format für einkommende E-Mails aus:",
"MSG_FORMAT_CHANGED":       u"> Das Format für einkommende E-Mails wurde geändert",
"MSG_RULES_CHANGED":        u"> Bedingungen wurden geändert",
"MSG_RULES_REMOVED":        u"> Bedingungen wurden gelöscht",
"CHANGE_SUBJ_RULES_MSG":    u"Du kannst nun die Bedingungen der Verarbeitung des Betreffes einer Nachricht anpassen. Du kannst z.B. $string1 mit $string2 ersetzen. Bitte gebe diese strings Zeile für Zeile ein (nutze dafür Tab). Zum Beispiel: \nFoo\nBar\n\nWenn du nur eine Zeile schreibst, wird diese Unterzeile gelöscht.\nDu kannst auch reguläre Ausdrücke verwenden.",
"CHANGE_BODY_RULES_MSG":    u"Du kannst nun die Bedingungen der Verarbeitung des Textes einer Nachricht anpassen. Du kannst z.B. $string1 mit $string2 ersetzen. Bitte gebe diese strings Zeile für Zeile ein (nutze dafür Tab). Zum Beispiel: \nFoo\nBar\n\nWenn du nur eine Zeile schreibst, wird diese Unterzeile gelöscht.\nDu kannst auch reguläre Ausdrücke verwenden.",
"CHANGE_SUBJ_RULES_ERROR":  u"Leider ist ein Fehler bei der Einstellung der Regeln für den Betreff aufgetreten. Bist du dir sicher, dass du 2 Zeilen gesendet hast? Versuche es erneut oder drücke auf Abbruch.",
"CHANGE_BODY_RULES_ERROR":  u"Leider ist ein Fehler bei der Einstellung der Regeln für den Text aufgetreten. Bist du dir sicher, dass du 2 Zeilen gesendet hast? Versuche es erneut oder drücke auf Abbruch.",
}
