# -*- coding: utf-8 -*-

LANG_KEY = u"EN"
LANG_NATIVE_NAME = u"English"

KWDS = {
"MSG_FORMAT_DEFAULT":       u"default: EMAIL [SUBJ.] MSG LNK",
"MSG_FORMAT_WO_LINK":       u"without_link: EMAIL [SUBJ.] MSG",
"MSG_FORMAT_LINK_ONLY":     u"link_only: EMAIL [SUBJ.] LNK",
"MSG_FORMAT_SHORT":         u"short: SUBJECT",
"CHANGE_MSG_FORMAT":        u"/msg_format - Change msg format",
"CHANGE_SUBJ_RULES":        u"/subj_rules - Subject rules",
"CHANGE_BODY_RULES":        u"/body_rules - Processing rules",
"HIDE_KEYBOARD":            u"/hide - Hide this keyboard",
"GO_PAY":                   u"GO TO THE PAYMENT SYSTEM",
"CANCEL":                   u"Cancel",
"REMOVE_RULES_BUTTON":      u"Remove all rules",
"CHECK_PAYMENT":            u"Check payment status",
"CONFIRM_ORDER":            u"Confirm action",
"SUCCESS_PAYMENT":          u"> Yay! Username {} now is yours. Btw you can receive all your aliases using command /addresses",
"NOT_PAID":                 u"> Still not paid!",
"CANCELLED":                u"> Cancelled",
"ENTER_SUBJ":               u"> Enter the Subject:",
"ENTER_SUBJ_ERR":           u"> Error while setting subject",
"ENTER_MSG":                u"> Enter the Message:",
"ENTER_MSG_ERR":            u"> Error while setting the message text. Try again:",
"MSG_SENT":                 u"> Message was sent",
"MSG_QUEUED":               u"> The message was queued",
"MSG_NOT_SENT":             u"> Message was not sent",
"MSG_ERROR_SENT":           u"> Error while sending message",
"INCORR_SYMB":              u"> Incorrect symbols! Enter another one:",
"NAME_TAKEN":               u"> This username is already taken! Enter another one:",
"TRANS_ISSUE":              u"> Transaction issue. Contact support: @adastreamer",
"PAY_CALL":                 u"> Done! Your email address is almost ready. You just need to confirm this action.",
"PAY_BUTTON":               u"Make a payment",
"HI":                       u"> Hi, you\'re welcome! The default address for this chat is: {}@etlgr.com {}",
"HI_POSTFIX":               u" (minus is a part of address)",
"ENTER_SENDER":             u"> Enter your address you want to send the message from:",
"ENTER_SENDER_WRONG":       u"> This is not your address. Try again:",
"ENTER_EMAIL":              u"> Enter email address(es) of your recipients:",
"ENTER_EMAIL_ERR":          u"> Error while setting email(s). You may set up to 5 recipients. Try again:",
"CHOOSE_NAME":              u"> Choose your username (eg. andrew):",
"ADDRESSES_LIST_BASE":      u"> Your addresses:",
"CHOOSE_ACTION":            u"> Choose action:",
"CHOOSE_LANG":              u"> Choose language:",
"GET_ADDRESS":              u"/start - Get default address",
"CHANGE_LANG":              u"/lang - Change language",
"SEND_MSG":                 u"/send - Send a message",
"REGISTER_OWN":             u"/register - Get a personal address",
"GET_ADDRESSES":            u"/addresses - Your addresses",
"CHOOSE_RELEASE_ADDRESS":   u"> Choose address to release:",
"NO_ADDRESS_TO_RELEASE":    u"> You have no addresses. You may reserve one by typing /register command",
"RELEASE":                  u"/release - Release your address",
"WRONG_RELEASE_ADDRESS":    u"> Wrong address. Try again:",
"RELEASED_CHOOSE_ACTION":   u"> Released! Choose action:",
"KEYBOARD_HIDDEN":          u"> Keyboard is hidden. You may also show all the actions by typing /start command",
"CHOOSE_MSG_FORMAT":        u"> Choose the format of incoming messages:",
"MSG_FORMAT_CHANGED":       u"> Format of incoming messages changed",
"MSG_RULES_CHANGED":        u"> Processing rules changed",
"MSG_RULES_REMOVED":        u"> Processing rules removed",
"CHANGE_SUBJ_RULES_MSG":    u"You may change the processing rules of the subject of messages. You may replace $string1 with $string2. Please enter these strings line by line (using new line wrap). For example: \nFoo\nBar\n\nIf you enter only one line, this substring will be removed.\nYou may also use regular expressions.",
"CHANGE_BODY_RULES_MSG":    u"You may change the processing rules of the body of messages. You may replace $string1 with $string2. Please enter these strings line by line (using new line wrap). For example: \nFoo\nBar\n\nIf you enter only one line, this substring will be removed.\nYou may also use regular expressions.",
"CHANGE_SUBJ_RULES_ERROR":  u"Error while setting the subject rules. Are you sure you've entered 2 lines? Try again or cancel:",
"CHANGE_BODY_RULES_ERROR":  u"Error while setting the body rules. Are you sure you've entered 2 lines? Try again or cancel:",
}
