# -*- coding: utf-8 -*-

LANG_KEY = u"ES"
LANG_NATIVE_NAME = u"Español"

KWDS = {
"MSG_FORMAT_DEFAULT":       u"predeterminado: CORREO [ASUNTO] ENLACE DEL MENSAJE",
"MSG_FORMAT_WO_LINK":       u"sin_enlace: CORREO [ASUNTO] MENSAJE",
"MSG_FORMAT_LINK_ONLY":     u"solamente_enlace: CORREO [ASUNTO] ENLACE",
"MSG_FORMAT_SHORT":         u"corto: ASUNTO",
"CHANGE_MSG_FORMAT":        u"/msg_format - Cambiar formato de mensaje",
"CHANGE_SUBJ_RULES":        u"/subj_rules - Reglas del asunto",
"CHANGE_BODY_RULES":        u"/body_rules - Reglas del procesamiento",
"HIDE_KEYBOARD":            u"/hide - Ocultar este teclado",
"GO_PAY":                   u"IR AL SISTEMA DE PAGO",
"CANCEL":                   u"Cancelar",
"REMOVE_RULES_BUTTON":      u"Eliminar todas las reglas",
"CHECK_PAYMENT":            u"Comprobar el estado del pago",
"CONFIRM_ORDER":            u"Confirmar acción",
"SUCCESS_PAYMENT":          u"> ¡Super! El nombre de usuario {} ahora es tuyo. Por cierto, puedes recibir todos tus alias utilizando el comando /addresses",
"NOT_PAID":                 u"> ¡Todavía sin pagar!",
"CANCELLED":                u"> Cancelado",
"ENTER_SUBJ":               u"> Introduzca el asunto:",
"ENTER_SUBJ_ERR":           u"> Error al establecer el asunto",
"ENTER_MSG":                u"> Introduzca el mensaje:",
"ENTER_MSG_ERR":            u"> Error al establecer el mensaje. Vuelve a intentarlo:",
"MSG_SENT":                 u"> Mensaje enviado",
"MSG_QUEUED":               u"> Mensaje puesto en la cola",
"MSG_NOT_SENT":             u"> Mensaje no enviado",
"MSG_ERROR_SENT":           u"> Error al enviar el mensaje",
"INCORR_SYMB":              u"> ¡Símbolos incorrectos! Introduzca otros:",
"NAME_TAKEN":               u"> ¡Este nombre de usuario ya está en uso! Introduzca otro:",
"TRANS_ISSUE":              u"> Problema de transacción. Contacte al soporte: @adastreamer",
"PAY_CALL":                 u"> ¡Hecho! Tu dirección de correo electrónico está casi lista. Sólo tienes que confirmar esta acción.",
"PAY_BUTTON":               u"Realizar un pago",
"HI":                       u"> ¡Hola, bienvenido! La dirección predeterminada para este chat es: {}@etlgr.com {}",
"HI_POSTFIX":               u" (menos es una parte de la dirección)",
"ENTER_SENDER":             u"> Introduzca la dirección de la que desea enviar el mensaje:",
"ENTER_SENDER_WRONG":       u"> Esta no es tu dirección. Vuelve a intentarlo:",
"ENTER_EMAIL":              u"> Introduzca la(s) dirección(es) de correo electrónico de sus destinatarios:",
"ENTER_EMAIL_ERR":          u"> Error al establecer el(los) correo(s). Puedes establecer hasta 5 destinatarios. Vuelve a intentarlo:",
"CHOOSE_NAME":              u"> Elige tu nombre de usuario (ej. andrew):",
"ADDRESSES_LIST_BASE":      u"> Tus direcciones:",
"CHOOSE_ACTION":            u"> Elige una acción:",
"CHOOSE_LANG":              u"> Elige un idioma:",
"GET_ADDRESS":              u"/start - Obtener dirección predeterminada",
"CHANGE_LANG":              u"/lang - Cambiar idioma",
"SEND_MSG":                 u"/send - Enviar un mensaje",
"REGISTER_OWN":             u"/register - Obtener una dirección personal",
"GET_ADDRESSES":            u"/addresses - Tus direcciones",
"CHOOSE_RELEASE_ADDRESS":   u"> Elige la dirección a liberar:",
"NO_ADDRESS_TO_RELEASE":    u"> No tienes direcciones. Puedes reservar una utilizando el comando /register",
"RELEASE":                  u"/release - Liberar tu dirección",
"WRONG_RELEASE_ADDRESS":    u"> Dirección incorrecta. Vuelve a intentarlo:",
"RELEASED_CHOOSE_ACTION":   u"> ¡Liberada! Elige una acción:",
"KEYBOARD_HIDDEN":          u"> El teclado está oculto. También puedes mostrar todas las acciones utilizando el comando /start",
"CHOOSE_MSG_FORMAT":        u"> Elige el formato de los mensajes entrantes:",
"MSG_FORMAT_CHANGED":       u"> Se ha cambiado el formato de los mensajes entrantes",
"MSG_RULES_CHANGED":        u"> Se han cambiado las reglas de procesamiento",
"MSG_RULES_REMOVED":        u"> Se han eliminado las reglas de procesamiento",
"CHANGE_SUBJ_RULES_MSG":    u"Puedes cambiar las reglas de procesamiento del asunto de los mensajes. Puedes reemplazar $string1 con $string2. Por favor, introduzca esos textos línea por línea (utilizando un salto de línea). Por ejemplo: \nFoo\nBar\n\nSi introduces sólo una línea, esa sublínea se eliminará.\nTambién puedes utilizar expresiones regulares.",
"CHANGE_BODY_RULES_MSG":    u"Puedes cambiar las reglas de procesamiento del cuerpo de los mensajes. Puedes reemplazar $string1 con $string2. Por favor, introduzca esos textos línea por línea (utilizando un salto de línea). Por ejemplo: \nFoo\nBar\n\nSi introduces sólo una línea, esa sublínea se eliminará.\nTambién puedes utilizar expresiones regulares.",
"CHANGE_SUBJ_RULES_ERROR":  u"Error al establecer las reglas del asunto. ¿Estás seguro de haber introducido 2 líneas? Vuelve a intentarlo o cancela:",
"CHANGE_BODY_RULES_ERROR":  u"Error al establecer las reglas del cuerpo. ¿Estás seguro de haber introducido 2 líneas? Vuelve a intentarlo o cancela:",
}
