# -*- coding: utf-8 -*-

LANG_KEY = u"IT"
LANG_NATIVE_NAME = u"Italiano"

KWDS = {
"MSG_FORMAT_DEFAULT":       u"predefinito: EMAIL [OGG.] MSG LNK",
"MSG_FORMAT_WO_LINK":       u"senza_link: EMAIL [OGG.] MSG",
"MSG_FORMAT_LINK_ONLY":     u"solo_link: EMAIL [OGG.] LNK",
"MSG_FORMAT_SHORT":         u"breve: OGGETTO",
"CHANGE_MSG_FORMAT":        u"/msg_format - Cambia formato messaggio",
"CHANGE_SUBJ_RULES":        u"/subj_rules - Regole oggetto",
"CHANGE_BODY_RULES":        u"/body_rules - Regole di elaborazione",
"HIDE_KEYBOARD":            u"/hide - Nascondi questa tastiera",
"GO_PAY":                   u"VAI AL SISTEMA DI PAGAMENTO",
"CANCEL":                   u"Cancella",
"REMOVE_RULES_BUTTON":      u"Rimuovi tutte le regole",
"CHECK_PAYMENT":            u"Controlla lo stato del pagamento",
"CONFIRM_ORDER":            u"Conferma l\'azione",
"SUCCESS_PAYMENT":          u"> Sìì! L\'username {} è ora tuo. Poi è possibile ricevere tutti gli alias utilizzando il comando /addresses",
"NOT_PAID":                 u"> Ancora non pagato!",
"CANCELLED":                u"> Cancellato",
"ENTER_SUBJ":               u"> Inserisci l\'Oggetto:",
"ENTER_SUBJ_ERR":           u"> Errore durante l\'impostazione dell\'oggetto",
"ENTER_MSG":                u"> Inserisci il Messaggio:",
"ENTER_MSG_ERR":            u"> Errore durante l\'impostazione del testo del messaggio. Riprova:",
"MSG_SENT":                 u"> Messaggio inviato",
"MSG_QUEUED":               u"> Messaggio in coda",
"MSG_NOT_SENT":             u"> Il messaggio non è stato inviato",
"MSG_ERROR_SENT":           u"> Errore durante l\'invio del messaggio",
"INCORR_SYMB":              u"> Simboli non corretti! Inserisci un altro:",
"NAME_TAKEN":               u"> Questo nome utente è già stato preso! Inseriscine un altro:",
"TRANS_ISSUE":              u"> Errore di transazione. Contattare il supporto: @adastreamer",
"PAY_CALL":                 u"> Fatto! Il tuo indirizzo email è quasi pronto. Devi solo confermare questa azione.",
"PAY_BUTTON":               u"Effettua un pagamento",
"HI":                       u"> Ciao, benvenuto! L\'indirizzo predefinito di questa chat è: {}@etlgr.com {}",
"HI_POSTFIX":               u" (meno è una parte dell\'indirizzo)",
"ENTER_SENDER":             u"> Inserisci l\'indirizzo da cui desideri inviare il messaggio:",
"ENTER_SENDER_WRONG":       u"> Questo non è il tuo indirizzo. Riprova:",
"ENTER_EMAIL":              u"> Inserisci l\'(gli) indirizzo(i) email dei destinatari:",
"ENTER_EMAIL_ERR":          u"> Errore durante l\'impostazione delle email. È possibile impostare fino a 5 destinatari. Riprova:",
"CHOOSE_NAME":              u"> Scegli il tuo nome utente (es. Andrew):",
"ADDRESSES_LIST_BASE":      u"> I tuoi indirizzi:",
"CHOOSE_ACTION":            u"> Scegli un\'azione:",
"CHOOSE_LANG":              u"> Scegli la lingua:",
"GET_ADDRESS":              u"/start - Ottieni l\'indirizzo predefinito",
"CHANGE_LANG":              u"/lang - Cambia lingua",
"SEND_MSG":                 u"/send - Invia un messaggio",
"REGISTER_OWN":             u"/register - Ottieni un indirizzo personale",
"GET_ADDRESSES":            u"/addresses - I tuoi indirizzi",
"CHOOSE_RELEASE_ADDRESS":   u"> Scegli l\'indirizzo da rilasciare:",
"NO_ADDRESS_TO_RELEASE":    u"> Non hai indirizzi. È possibile riservarne uno con il comando /register",
"RELEASE":                  u"/release - Rilascia il tuo indirizzo",
"WRONG_RELEASE_ADDRESS":    u"> Indirizzo sbagliato. Riprova:",
"RELEASED_CHOOSE_ACTION":   u"> Rilasciato! Scegli un\'azione:",
"KEYBOARD_HIDDEN":          u"> La tastiera è nascosta. Puoi anche mostrare tutte le azioni digitando il comando /start",
"CHOOSE_MSG_FORMAT":        u"> Scegli il formato dei messaggi in arrivo:",
"MSG_FORMAT_CHANGED":       u"> Il formato dei messaggi in arrivo è stato modificato",
"MSG_RULES_CHANGED":        u"> Regole di elaborazione cambiate",
"MSG_RULES_REMOVED":        u"> Regole di elaborazione rimosse",
"CHANGE_SUBJ_RULES_MSG":    u"È possibile modificare le regole di elaborazione dell\'oggetto dei messaggi. È possibile sostituire $string1 con $string2. Inserisci queste righe lineari per riga (utilizzando un ritorno a capo). Ad esempio: \nFoo\nBar\n\nSe si immette una sola riga, questa sottostringa verrà rimossa.\nÈ anche possibile utilizzare espressioni regolari.",
"CHANGE_BODY_RULES_MSG":    u"È possibile modificare le regole di elaborazione del corpo dei messaggi. È possibile sostituire $string1 con $string2. Inserisci queste righe lineari per riga (utilizzando un ritorno a capo). Ad esempio: \nFoo\nBar\n\nSe si immette una sola riga, questa sottostringa verrà rimossa.\nÈ anche possibile utilizzare espressioni regolari.",
"CHANGE_SUBJ_RULES_ERROR":  u"Errore durante l\'impostazione delle regole dell\'oggetto. Sei sicuro di aver inserito 2 righe? Prova nuovamente o annulla:",
"CHANGE_BODY_RULES_ERROR":  u"Errore durante l\'impostazione delle regole del corpo. Sei sicuro di aver inserito 2 righe? Prova nuovamente o annulla:",
}
