# -*- coding: utf-8 -*-

LANG_KEY = u"TR"
LANG_NATIVE_NAME = u"Türkçe"

KWDS = {
"MSG_FORMAT_DEFAULT":       u"varsayılan: E- Mail [KONU] MESAJ BAGLANTI",
"MSG_FORMAT_WO_LINK":       u"bağlantısız: E-Mail [KONU] MESAJ",
"MSG_FORMAT_LINK_ONLY":     u"tek_bağlantı: E-Mail [KONU] BAGLANTI",
"MSG_FORMAT_SHORT":         u"kısa: KONU",
"CHANGE_MSG_FORMAT":        u"/msg_format – Mesaj biçimini değiştir",
"CHANGE_SUBJ_RULES":        u"/subj_rules – Konu kuralları",
"CHANGE_BODY_RULES":        u"/body_rules – İşleme kuralları",
"HIDE_KEYBOARD":            u"/hide – Klavyeyi gizle",
"GO_PAY":                   u"Ödeme sistemine git",
"CANCEL":                   u"İptal",
"REMOVE_RULES_BUTTON":      u"Tüm kuralları kaldırın",
"CHECK_PAYMENT":            u"Ödeme durumu kontrol",
"CONFIRM_ORDER":            u"Eylemi onayla",
"SUCCESS_PAYMENT":          u"> Süper! Kullanıcı adı {} artık senin. /addresses komutunu kullanarak adreslerinizi görebilirsiniz",
"NOT_PAID":                 u"> Hala ödenmedi!",
"CANCELLED":                u"> İptal edildi",
"ENTER_SUBJ":               u"> Konuyu giriniz:",
"ENTER_SUBJ_ERR":           u"> Konu ayarlanırken hata oluştu",
"ENTER_MSG":                u"> Mesajınızı giriniz:",
"ENTER_MSG_ERR":            u"> Mesaj metni ayarlanırken hata oluştu. Tekrar dene:",
"MSG_SENT":                 u"> Mesaj gönderildi",
"MSG_QUEUED":               u"> İleti sıraya alındı",
"MSG_NOT_SENT":             u"> Mesaj gönderilemedi",
"MSG_ERROR_SENT":           u"> Mesaj gönderilirken hata oluştu",
"INCORR_SYMB":              u"> Geçersiz karakter kullanıldı! Tekrar deneyin:",
"NAME_TAKEN":               u"> Bu kullanıcı adı daha önce alınmış! Başka bir kullanıcı adı giriniz:",
"TRANS_ISSUE":              u"> İşlem sorunu. İletişim desteği: @adastreamer",
"PAY_CALL":                 u"> Bitti! E-Posta işleminiz neredeyse hazır. Bu işlemi onaylamanız yeterlidir.",
"PAY_BUTTON":               u"Ödeme yap",
"HI":                       u"> Merhaba, hoş geldin. Bu bot için varsayılan adres:{} @etlgr.com {}",
"HI_POSTFIX":               u" (Eksi adresin bir parçasıdır)",
"ENTER_SENDER":             u"> Mesajı göndermek istediğiniz adresi giriniz:",
"ENTER_SENDER_WRONG":       u"> Bu senin adresin değil. Tekrar dene:",
"ENTER_EMAIL":              u"> Alıcı E-Posta adresini(adreslerini) giriniz:",
"ENTER_EMAIL_ERR":          u"> E-posta ayarlanırken hata oluştu. En fazla 5 alıcı ayarlayabilirsiniz. Tekrar dene:",
"CHOOSE_NAME":              u"> Kullanıcı adınızı seçin(Örnek: mehmetali):",
"ADDRESSES_LIST_BASE":      u"> Adresleriniz:",
"CHOOSE_ACTION":            u"> İşlem seçin:",
"CHOOSE_LANG":              u"> Dili değiştir:",
"GET_ADDRESS":              u"/start – Varsayılan adresi al.",
"CHANGE_LANG":              u"/lang – Dili değiştir",
"SEND_MSG":                 u"/send – Mail gönderin",
"REGISTER_OWN":             u"/register – Kişisel adresinizi alın",
"GET_ADDRESSES":            u"/addresses - Adresleriniz",
"CHOOSE_RELEASE_ADDRESS":   u"> Bırakmak istediğiniz adresi seçin:",
"NO_ADDRESS_TO_RELEASE":    u"> Adresin yok. /register komutunu yazarak birini adres alabilirsiniz",
"RELEASE":                  u"/release – Adresinizi bırakın",
"WRONG_RELEASE_ADDRESS":    u"> Yanlış adres. Tekrar dene:",
"RELEASED_CHOOSE_ACTION":   u"> Bırakıldı. Başka bir eylem seçin:",
"KEYBOARD_HIDDEN":          u"> Klavye gizlendi. Ayrıca, /start komutunu yazarak tüm işlemleri gösterebilirsiniz",
"CHOOSE_MSG_FORMAT":        u"> Gelen mesajların formatını seçin:",
"MSG_FORMAT_CHANGED":       u"> Gelen mesajların formatı değişti",
"MSG_RULES_CHANGED":        u"> İşleme kuralları değişti",
"MSG_RULES_REMOVED":        u"> İşleme kuralları kaldırıldı",
"CHANGE_SUBJ_RULES_MSG":    u"Mesajların konusunun işleme kurallarını değiştirebilirsiniz. $ String1 ile $ string2'yi değiştirebilirsiniz. Lütfen bu dizeleri satır satırlarla girin (yeni satır sarması kullanarak). Örneğin \nFoo \nBar \n \nIf Yalnızca bir satır girerseniz bu alt yazı kaldırılır. \nYou Düzenli ifadeler de kullanabilir.",
"CHANGE_BODY_RULES_MSG":    u"İleti gövdesinin işlem kurallarını değiştirebilirsiniz. $ String1 ile $ string2'yi değiştirebilirsiniz. Lütfen bu dizeleri satır satırlarla girin (yeni satır sarması kullanarak). Örneğin \nFoo\nBar\n\nIf Yalnızca bir satır girerseniz bu alt yazı kaldırılır. \nYou Düzenli ifadeler de kullanabilir.",
"CHANGE_SUBJ_RULES_ERROR":  u"Konu kuralları oluşturulurken hata oluştu. 2 satır girdiğinizden emin misiniz? Tekrar dene veya iptal et.",
"CHANGE_BODY_RULES_ERROR":  u"Konu kuralları belirlenirken hata oluştu. 2 satır girdiğinizden emin misiniz? Tekrar dene veya iptal et.",
}
