# -*- coding: utf-8 -*-

LANG_KEY = u"zh_HK"
LANG_NATIVE_NAME = u"Traditional Chinese (Hong Kong)"

KWDS = {
"MSG_FORMAT_DEFAULT":       u"預設: 電郵地址 [標題] 內容 超連結",
"MSG_FORMAT_WO_LINK":       u"沒有超連結: 電郵地址 [標題] 內容",
"MSG_FORMAT_LINK_ONLY":     u"只有超連結: 電郵地址 [標題] 超連結",
"MSG_FORMAT_SHORT":         u"簡短: 內容",
"CHANGE_MSG_FORMAT":        u"/msg_format - 更改訊息格式",
"CHANGE_SUBJ_RULES":        u"/subj_rules - 標題規則",
"CHANGE_BODY_RULES":        u"/body_rules - 處理規則",
"HIDE_KEYBOARD":            u"/hide - 隱藏此鍵盤",
"GO_PAY":                   u"前往付帳系統",
"CANCEL":                   u"取消",
"REMOVE_RULES_BUTTON":      u"刪除所有規則",
"CHECK_PAYMENT":            u"檢視付帳狀態",
"CONFIRM_ORDER":            u"確定操作",
"SUCCESS_PAYMENT":          u"> 太好了! 現在 {} 是屬於你的。 你亦可以透過 /addresses 使用你其他的別名接收訊息。",
"NOT_PAID":                 u"> 仍未支帳!",
"CANCELLED":                u"> 已取消",
"ENTER_SUBJ":               u"> 輸入標題:",
"ENTER_SUBJ_ERR":           u"> 設定標題時發生錯誤",
"ENTER_MSG":                u"> 輸入內容:",
"ENTER_MSG_ERR":            u"> 設定內容時發生錯誤，請重新再試:",
"MSG_SENT":                 u"> 訊息已送出",
"MSG_QUEUED":               u"> 訊息已排程送出",
"MSG_NOT_SENT":             u"> 訊息未能送出",
"MSG_ERROR_SENT":           u"> 送出訊息時發生錯誤",
"INCORR_SYMB":              u"> 符號不正確! 請重新再試:",
"NAME_TAKEN":               u"> 此用戶名已被使用! 請輸入其他名稱:",
"TRANS_ISSUE":              u"> 交易出現問題。 請聯絡技術支援: @adastreamer",
"PAY_CALL":                 u"> 完成! 你的電郵地址快將啟用。你只需確定此操作繼續。",
"PAY_BUTTON":               u"付款",
"HI":                       u"> 你好, 你在這個對話的預設電郵地址是: {}@etlgr.com {}",
"HI_POSTFIX":               u" (減號是電郵地址的一部份)",
"ENTER_SENDER":             u"> 請選擇你要用作寄件的地址:",
"ENTER_SENDER_WRONG":       u"> 這個不是你的電郵地址，請再試一次:",
"ENTER_EMAIL":              u"> 請輸入收件人:",
"ENTER_EMAIL_ERR":          u"> 設定電郵時發生錯誤。你最多可以傳送至5位收件人，請再試一次:",
"CHOOSE_NAME":              u"> 請輸入你的用戶名 (例如: andrew):",
"ADDRESSES_LIST_BASE":      u"> 你的地址:",
"CHOOSE_ACTION":            u"> 選擇操作:",
"CHOOSE_LANG":              u"> 選擇語言:",
"GET_ADDRESS":              u"/start - 取得預設電郵地址",
"CHANGE_LANG":              u"/lang - 更改語言",
"SEND_MSG":                 u"/send - 傳送電子郵件",
"REGISTER_OWN":             u"/register - 登記個人電郵地址",
"GET_ADDRESSES":            u"/addresses - 你的電郵地址",
"CHOOSE_RELEASE_ADDRESS":   u"> 請選擇要放棄的電郵地址:",
"NO_ADDRESS_TO_RELEASE":    u"> 你沒有任何電郵地址. 你可以使用 /register 命令取得一個新的個人電郵地址",
"RELEASE":                  u"/release - 放棄你的電郵地址",
"WRONG_RELEASE_ADDRESS":    u"> 電郵地址錯誤，請重新再試:",
"RELEASED_CHOOSE_ACTION":   u"> 已放棄! 請選擇操作選項:",
"KEYBOARD_HIDDEN":          u"> 鍵盤已隱藏。 你可以使用 /start 命令顯示所有操作選項",
"CHOOSE_MSG_FORMAT":        u"> 更改傳入電郵的格式:",
"MSG_FORMAT_CHANGED":       u"> 傳入電郵的格式已更改",
"MSG_RULES_CHANGED":        u"> 處理規則已更改",
"MSG_RULES_REMOVED":        u"> 處理規則已刪除",
"CHANGE_SUBJ_RULES_MSG":    u"你可以更改處理電郵標題的規則。 你可以使用 $string1 取代 $string2 。 請一行接一行輸入這些字符 (請開新行)。 例如: \nFoo\nBar\n\n如果你只輸入一行，這個紀錄會被刪除。\n你亦可以使用常規表達式。",
"CHANGE_BODY_RULES_MSG":    u"你可以更改處理電郵內容的規則。  你可以使用 $string1 取代 $string2 。 請一行接一行輸入這些字符 (請開新行)。 例如: \nFoo\nBar\n\n如果你只輸入一行，這個紀錄會被刪除。\n你亦可以使用常規表達式。",
"CHANGE_SUBJ_RULES_ERROR":  u"設定標題規則時發生錯誤。 你是否已經輸入2行紀錄? 再試一次或取消:",
"CHANGE_BODY_RULES_ERROR":  u"設定內容規則時發生錯誤。 你是否已經輸入2行紀錄? 再試一次或取消:",
}
